package com.localapi;

import org.json.JSONArray;
import org.json.JSONObject;

/**
 * Phase 4b: friend relationships — real persistent state on top of StateStore.
 *
 * Per-user state (inside the user's "state" object):
 *   friends        : [userId, ...]            accepted friends
 *   blacklist      : [userId, ...]            blacklisted users
 *   aliases        : { "<userId>": alias }    caller-local nickname overrides
 *   friendRequestsIn : [{userId, msg, at, status}]  received requests
 *       status: 0 pending, 2 accepted, 3 rejected
 *
 * People are either real accounts (StateStore users) or citizens (the
 * persistent NPC population generated by GameCatalog). Presence is derived
 * from real state: a real user is online iff it holds at least one un-dropped
 * access token; citizens are always offline.
 */
final class Friend {

    private Friend() {}

    public static final int MAX_FRIENDS = 100;

    // ------------------------------------------------------------ lookups

    /** The user/citizen record for an id — real users first, then citizens. */
    public static JSONObject person(StateStore store, long userId) {
        if (userId <= 0) return null;
        JSONObject u = store.findByUserId(userId);
        if (u != null) return u;
        JSONArray citizens = GameCatalog.citizens(store);
        for (int i = 0; citizens != null && i < citizens.length(); i++) {
            JSONObject c = citizens.optJSONObject(i);
            if (c != null && c.optLong("userId") == userId) return c;
        }
        return null;
    }

    public static boolean isCitizen(StateStore store, long userId) {
        return store.findByUserId(userId) == null && person(store, userId) != null;
    }

    /** Online presence from real state: live token(s) => online. */
    public static boolean online(StateStore store, long userId) {
        return store.isOnline(userId);
    }

    // ------------------------------------------------------------ user state

    private static JSONObject st(StateStore store, JSONObject user) {
        return store.userState(user);
    }

    private static JSONArray ids(StateStore store, JSONObject user, String key) {
        JSONArray a = st(store, user).optJSONArray(key);
        return a == null ? new JSONArray() : a;
    }

    public static boolean isFriend(StateStore store, JSONObject user, long otherId) {
        return contains(ids(store, user, "friends"), otherId);
    }

    public static boolean isBlacklisted(StateStore store, JSONObject user, long otherId) {
        return contains(ids(store, user, "blacklist"), otherId);
    }

    private static boolean contains(JSONArray arr, long id) {
        for (int i = 0; i < arr.length(); i++) {
            if (arr.optLong(i) == id) return true;
        }
        return false;
    }

    private static void addId(StateStore store, JSONObject user, String key, long id) {
        JSONArray a = ids(store, user, key);
        if (!contains(a, id)) {
            a.put(id);
            st(store, user).put(key, a);
        }
    }

    private static void removeId(StateStore store, JSONObject user, String key, long id) {
        JSONArray a = ids(store, user, key);
        JSONArray next = new JSONArray();
        for (int i = 0; i < a.length(); i++) {
            if (a.optLong(i) != id) next.put(a.optLong(i));
        }
        st(store, user).put(key, next);
    }

    public static String aliasOf(StateStore store, JSONObject user, long otherId) {
        JSONObject aliases = st(store, user).optJSONObject("aliases");
        return aliases == null ? "" : aliases.optString(String.valueOf(otherId));
    }

    /** Pending requests received by the user (status 0). */
    public static JSONArray pendingRequests(StateStore store, JSONObject user) {
        JSONArray all = st(store, user).optJSONArray("friendRequestsIn");
        JSONArray out = new JSONArray();
        for (int i = 0; all != null && i < all.length(); i++) {
            JSONObject r = all.optJSONObject(i);
            if (r != null && r.optInt("status") == 0) out.put(r);
        }
        return out;
    }

    // ------------------------------------------------------------ actions

    /** POST /friend/api/v1/friends {friendId, msg}. Citizens auto-accept. */
    public static String add(StateStore store, JSONObject user, long friendId, String msg) {
        if (friendId <= 0) return "bad friendId";
        if (friendId == user.optLong("userId")) return "cannot add yourself";
        if (isBlacklisted(store, user, friendId)) return "user is blacklisted";
        if (isFriend(store, user, friendId)) return "already friends";
        if (person(store, friendId) == null) return "user not found";
        if (friends(store, user).length() >= MAX_FRIENDS) return "friend list is full";

        JSONObject target = store.findByUserId(friendId);
        if (target == null) {
            // citizen: nobody to approve — the request resolves immediately
            addId(store, user, "friends", friendId);
            store.save();
            return null;
        }
        JSONArray reqs = st(store, target).optJSONArray("friendRequestsIn");
        if (reqs == null) {
            reqs = new JSONArray();
        }
        for (int i = 0; i < reqs.length(); i++) {
            JSONObject r = reqs.optJSONObject(i);
            if (r != null && r.optLong("userId") == user.optLong("userId")
                    && r.optInt("status") == 0) {
                return "request already pending";
            }
        }
        JSONObject r = new JSONObject();
        r.put("userId", user.optLong("userId"));
        r.put("msg", msg == null ? "" : msg);
        r.put("at", System.currentTimeMillis());
        r.put("status", 0);
        reqs.put(r);
        st(store, target).put("friendRequestsIn", reqs);
        store.save();
        return null;
    }

    /** PUT /friend/api/v1/friends/{friendId}/agreement — accept a received request. */
    public static String accept(StateStore store, JSONObject user, long otherId) {
        JSONArray reqs = st(store, user).optJSONArray("friendRequestsIn");
        boolean hit = false;
        for (int i = 0; reqs != null && i < reqs.length(); i++) {
            JSONObject r = reqs.optJSONObject(i);
            if (r != null && r.optLong("userId") == otherId && r.optInt("status") == 0) {
                r.put("status", 2);
                hit = true;
            }
        }
        if (!hit) return "no pending request";
        if (friends(store, user).length() >= MAX_FRIENDS) return "friend list is full";
        addId(store, user, "friends", otherId);
        JSONObject other = store.findByUserId(otherId);
        if (other != null) {
            addId(store, other, "friends", user.optLong("userId"));
        }
        store.save();
        return null;
    }

    /** PUT /friend/api/v1/friends/{friendId}/rejection. */
    public static String reject(StateStore store, JSONObject user, long otherId) {
        JSONArray reqs = st(store, user).optJSONArray("friendRequestsIn");
        boolean hit = false;
        for (int i = 0; reqs != null && i < reqs.length(); i++) {
            JSONObject r = reqs.optJSONObject(i);
            if (r != null && r.optLong("userId") == otherId && r.optInt("status") == 0) {
                r.put("status", 3);
                hit = true;
            }
        }
        if (!hit) return "no pending request";
        store.save();
        return null;
    }

    /** DELETE /friend/api/v1/friends?friendId= — remove friendship both sides. */
    public static String remove(StateStore store, JSONObject user, long otherId) {
        if (!isFriend(store, user, otherId)) return "not friends";
        removeId(store, user, "friends", otherId);
        JSONObject other = store.findByUserId(otherId);
        if (other != null) {
            removeId(store, other, "friends", user.optLong("userId"));
        }
        store.save();
        return null;
    }

    /** DELETE /friend/api/v1/friends/black?friendId= — add to blacklist (unfriends). */
    public static String blacklist(StateStore store, JSONObject user, long otherId) {
        if (person(store, otherId) == null) return "user not found";
        if (otherId == user.optLong("userId")) return "cannot blacklist yourself";
        remove(store, user, otherId);
        addId(store, user, "blacklist", otherId);
        store.save();
        return null;
    }

    /** POST/DELETE alias. */
    public static String setAlias(StateStore store, JSONObject user, long otherId, String alias) {
        // "(alias)" suffix lets Handlers.failFriend map this to FriendOnError
        // 3003 "Can not modify alias for stranger" — remove() failures keep
        // the generic path (no client-specific code exists for them).
        if (!isFriend(store, user, otherId)) return "not friends (alias)";
        JSONObject aliases = st(store, user).optJSONObject("aliases");
        if (aliases == null) {
            aliases = new JSONObject();
        }
        if (alias == null || alias.isEmpty()) {
            aliases.remove(String.valueOf(otherId));
        } else {
            aliases.put(String.valueOf(otherId), alias);
        }
        st(store, user).put("aliases", aliases);
        store.save();
        return null;
    }

    // ------------------------------------------------------------ reads

    public static JSONArray friends(StateStore store, JSONObject user) {
        return ids(store, user, "friends");
    }

    /** Friend JSON in the exact shape of the client's greendao Friend entity. */
    public static JSONObject personJson(StateStore store, JSONObject viewer, long userId) {
        JSONObject p = person(store, userId);
        if (p == null) return null;
        boolean real = store.findByUserId(userId) != null;
        JSONObject out = new JSONObject();
        out.put("ID", userId);
        out.put("userId", userId);
        out.put("localUserId", viewer == null ? 0 : viewer.optLong("userId"));
        out.put("nickName", p.optString("nickName"));
        out.put("picUrl", p.optString("headPic") == null || p.optString("headPic").isEmpty()
                ? p.optString("picUrl") : p.optString("headPic"));
        out.put("sex", p.optInt("sex"));
        out.put("age", 0);
        out.put("country", p.optString("country"));
        out.put("details", p.optString("details"));
        out.put("language", "en");
        out.put("expireDate", p.optString("expireDate"));
        out.put("vip", p.optInt("vip"));
        out.put("role", 0);
        out.put("starCode", p.optString("starCode"));
        out.put("clanId", p.optLong("clanId"));
        out.put("clanName", "");
        out.put("friend", viewer != null && isFriend(store, viewer, userId));
        out.put("status", online(store, userId) ? 1 : 0);
        out.put("logoutTime", 0L);
        out.put("gameId", "");
        out.put("gameName", "");
        out.put("alias", viewer == null ? "" : aliasOf(store, viewer, userId));
        out.put("isSearchById", false);
        return out;
    }

    /** StatusBean for one friend (gaming details unknown until GameServer phase). */
    public static JSONObject statusBean(StateStore store, long userId) {
        JSONObject out = new JSONObject();
        out.put("userId", userId);
        out.put("status", online(store, userId) ? 1 : 0);
        out.put("gameId", "");
        out.put("gameName", "");
        out.put("gamePic", "");
        out.put("gamingInfo", JSONObject.NULL);
        out.put("partyInfo", JSONObject.NULL);
        out.put("logoutTime", 0L);
        return out;
    }
}
