# GameServer on-device build (arm64) — generated by gen_android_mk.py
LOCAL_PATH := $(call my-dir)

GS_WORK ?= $(error GS_WORK must point to the assembled sources dir)
ROOT := $(GS_WORK)/extract
BH   := $(GS_WORK)/behaviac-src
LIBS := $(ROOT)/engine-core/dev/libraries
EDP  := $(ROOT)/engine-core/dev/engine/Dependencies
LDP  := $(ROOT)/dev/logic/dependencies
SDP  := $(ROOT)/dev/server/dependencies
CORE := $(ROOT)/engine-core/dev/engine/Src/Core
LOGIC := $(ROOT)/dev/logic/Src
SERVER := $(ROOT)/dev/server/src
SPLITS := $(call my-dir)/splits

WARNFLAGS := -Wno-logical-op-parentheses -Wno-bitwise-op-parentheses -Wno-deprecated-register \
  -Wno-shift-count-overflow -Wno-string-plus-int -Wno-tautological-compare -Wno-return-type \
  -Wno-switch -Wno-null-conversion -Wno-delete-non-virtual-dtor -Wno-self-assign-field \
  -Wno-empty-body -Wno-pointer-bool-conversion -Wno-unused-value -Wno-inconsistent-missing-override \
  -Wno-constant-conversion -Wno-format-security -Wno-parentheses -Wno-writable-strings \
  -Wno-undefined-var-template -Wno-deprecated-declarations

COMPAT := $(call my-dir)/compat/gs_compat.h
COMMON_FLAGS := -include $(COMPAT) -DLORD_FORCE_PLATFORM=LORD_PLATFORM_LINUX -DLORD_STATIC=1 \
  -D_FORCE_INLINES -DHAVE_PTHREAD -fexceptions -frtti -pthread -fpermissive -Wno-error -Wno-format -Wno-format-security -Wno-unused-but-set-variable $(WARNFLAGS)

#----------------------------------------------------------------------------------------
# zlib
include $(CLEAR_VARS)
LOCAL_MODULE := zlib
LOCAL_CFLAGS += -O1
LOCAL_C_INCLUDES += $(LIBS)/include/android/zlib
LOCAL_SRC_FILES := $(wildcard $(LIBS)/src/android/zlib/*.c)
include $(BUILD_STATIC_LIBRARY)

#----------------------------------------------------------------------------------------
# lua 5.1
include $(CLEAR_VARS)
LOCAL_MODULE := lua
LOCAL_CFLAGS += -O1
LOCAL_C_INCLUDES += $(LIBS)/src/android/lua
LOCAL_SRC_FILES := $(wildcard $(LIBS)/src/android/lua/*.c)
include $(BUILD_STATIC_LIBRARY)

#----------------------------------------------------------------------------------------
# g3log
include $(CLEAR_VARS)
LOCAL_MODULE := g3log
LOCAL_CFLAGS += -O1 $(COMMON_FLAGS)
LOCAL_C_INCLUDES += $(LIBS)/include/android/g3log
LOCAL_SRC_FILES := $(wildcard $(LIBS)/src/android/g3log/*.cpp) $(wildcard $(LIBS)/src/android/g3log/*.c)
include $(BUILD_STATIC_LIBRARY)

#----------------------------------------------------------------------------------------
# raknet
include $(CLEAR_VARS)
LOCAL_MODULE := raknet
LOCAL_CFLAGS += -O1 $(COMMON_FLAGS)
LOCAL_C_INCLUDES += $(LDP)/src/raknet/include
LOCAL_SRC_FILES := $(wildcard $(LDP)/src/raknet/include/*.cpp)
include $(BUILD_STATIC_LIBRARY)

#----------------------------------------------------------------------------------------
# freetype
include $(CLEAR_VARS)
LOCAL_MODULE := freetype
LOCAL_CFLAGS += -DFT2_BUILD_LIBRARY -O2
LOCAL_C_INCLUDES += $(LIBS)/include/android/freeType
LOCAL_C_INCLUDES += $(LIBS)/include/android/freeType/freetype
LOCAL_C_INCLUDES += $(LIBS)/src/android/freeType
LOCAL_SRC_FILES := 	$(LIBS)/src/android/freeType/autofit/autofit.c \
	$(LIBS)/src/android/freeType/bdf/bdf.c \
	$(LIBS)/src/android/freeType/cff/cff.c \
	$(LIBS)/src/android/freeType/base/ftbase.c \
	$(LIBS)/src/android/freeType/base/ftbitmap.c \
	$(LIBS)/src/android/freeType/cache/ftcache.c \
	$(LIBS)/src/android/freeType/base/ftfstype.c \
	$(LIBS)/src/android/freeType/base/ftgasp.c \
	$(LIBS)/src/android/freeType/base/ftglyph.c \
	$(LIBS)/src/android/freeType/gzip/ftgzip.c \
	$(LIBS)/src/android/freeType/base/ftinit.c \
	$(LIBS)/src/android/freeType/lzw/ftlzw.c \
	$(LIBS)/src/android/freeType/base/ftstroke.c \
	$(LIBS)/src/android/freeType/base/ftsystem.c \
	$(LIBS)/src/android/freeType/smooth/smooth.c \
	$(LIBS)/src/android/freeType/base/ftbbox.c \
	$(LIBS)/src/android/freeType/base/ftgxval.c \
	$(LIBS)/src/android/freeType/base/ftlcdfil.c \
	$(LIBS)/src/android/freeType/base/ftmm.c \
	$(LIBS)/src/android/freeType/base/ftotval.c \
	$(LIBS)/src/android/freeType/base/ftpatent.c \
	$(LIBS)/src/android/freeType/base/ftpfr.c \
	$(LIBS)/src/android/freeType/base/ftsynth.c \
	$(LIBS)/src/android/freeType/base/fttype1.c \
	$(LIBS)/src/android/freeType/base/ftwinfnt.c \
	$(LIBS)/src/android/freeType/base/ftxf86.c \
	$(LIBS)/src/android/freeType/pcf/pcf.c \
	$(LIBS)/src/android/freeType/pfr/pfr.c \
	$(LIBS)/src/android/freeType/psaux/psaux.c \
	$(LIBS)/src/android/freeType/pshinter/pshinter.c \
	$(LIBS)/src/android/freeType/psnames/psmodule.c \
	$(LIBS)/src/android/freeType/raster/raster.c \
	$(LIBS)/src/android/freeType/sfnt/sfnt.c \
	$(LIBS)/src/android/freeType/truetype/truetype.c \
	$(LIBS)/src/android/freeType/type1/type1.c \
	$(LIBS)/src/android/freeType/cid/type1cid.c \
	$(LIBS)/src/android/freeType/type42/type42.c \
	$(LIBS)/src/android/freeType/winfonts/winfnt.c
include $(BUILD_STATIC_LIBRARY)

#----------------------------------------------------------------------------------------
# freeimage
include $(CLEAR_VARS)
LOCAL_MODULE := freeimage
LOCAL_CFLAGS := -DFREEIMAGE_LIB=1 -DPNG_STATIC=1 -O1 -fno-strict-aliasing
LOCAL_C_INCLUDES += $(LIBS)/include/android/freeImage
LOCAL_C_INCLUDES += $(LIBS)/src/android/freeImage
LOCAL_C_INCLUDES += $(LIBS)/src/android/freeImage/Metadata
LOCAL_C_INCLUDES += $(LIBS)/src/android/freeImage/DeprecationManager
LOCAL_C_INCLUDES += $(LIBS)/src/android/freeImage/FreeImage
LOCAL_C_INCLUDES += $(LIBS)/src/android/freeImage/FreeImageToolkit
LOCAL_C_INCLUDES += $(LIBS)/src/android/freeImage/LibJPEG
LOCAL_C_INCLUDES += $(LIBS)/src/android/freeImage/LibPNG
LOCAL_C_INCLUDES += $(LIBS)/src/android/freeImage/LibMNG
LOCAL_C_INCLUDES += $(LIBS)/src/android/freeImage/LibOpenJPEG
LOCAL_C_INCLUDES += $(LIBS)/src/android/freeImage/LibTIFF
LOCAL_C_INCLUDES += $(LIBS)/src/android/freeImage/LibTIFF4
LOCAL_C_INCLUDES += $(LIBS)/src/android/freeImage/LibRawLite
LOCAL_C_INCLUDES += $(LIBS)/src/android/freeImage/LibRawLite/libraw
LOCAL_C_INCLUDES += $(LIBS)/src/android/freeImage/LibRawLite/internal
LOCAL_C_INCLUDES += $(LIBS)/src/android/freeImage/LibRawLite/dcraw
LOCAL_C_INCLUDES += $(LIBS)/src/android/freeImage/OpenEXR
LOCAL_C_INCLUDES += $(LIBS)/src/android/freeImage/OpenEXR/IlmImf
LOCAL_C_INCLUDES += $(LIBS)/src/android/freeImage/ZLib
LOCAL_SRC_FILES := 	$(LIBS)/src/android/freeImage/DeprecationManager/Deprecated.cpp \
	$(LIBS)/src/android/freeImage/DeprecationManager/DeprecationMgr.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/BitmapAccess.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/CacheFile.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/ColorLookup.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/Conversion.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/ConversionFloat.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/Conversion4.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/Conversion8.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/Conversion16_555.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/Conversion16_565.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/Conversion24.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/Conversion32.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/ConversionRGB16.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/ConversionRGBF.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/ConversionUINT16.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/ConversionType.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/FreeImage.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/FreeImageIO.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/GetType.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/Halftoning.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/J2KHelper.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/MemoryIO.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/MultiPage.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/NNQuantizer.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/PixelAccess.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/Plugin.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/PluginBMP.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/PluginDDS.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/PluginGIF.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/PluginHDR.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/PluginICO.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/PluginJPEG.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/PluginPNG.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/PluginTARGA.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/ToneMapping.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/tmoColorConvert.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/tmoDrago03.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/tmoFattal02.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/tmoReinhard05.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/WuQuantizer.cpp \
	$(LIBS)/src/android/freeImage/FreeImage/ZLibInterface.cpp \
	$(LIBS)/src/android/freeImage/FreeImageToolkit/Background.cpp \
	$(LIBS)/src/android/freeImage/FreeImageToolkit/Colors.cpp \
	$(LIBS)/src/android/freeImage/FreeImageToolkit/Flip.cpp \
	$(LIBS)/src/android/freeImage/FreeImageToolkit/Resize.cpp \
	$(LIBS)/src/android/freeImage/FreeImageToolkit/BSplineRotate.cpp \
	$(LIBS)/src/android/freeImage/FreeImageToolkit/CopyPaste.cpp \
	$(LIBS)/src/android/freeImage/FreeImageToolkit/JPEGTransform.cpp \
	$(LIBS)/src/android/freeImage/FreeImageToolkit/Channels.cpp \
	$(LIBS)/src/android/freeImage/FreeImageToolkit/Display.cpp \
	$(LIBS)/src/android/freeImage/FreeImageToolkit/MultigridPoissonSolver.cpp \
	$(LIBS)/src/android/freeImage/FreeImageToolkit/ClassicRotate.cpp \
	$(LIBS)/src/android/freeImage/FreeImageToolkit/Rescale.cpp \
	$(LIBS)/src/android/freeImage/LibJPEG/ckconfig.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jaricom.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jcapimin.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jcapistd.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jcarith.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jccoefct.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jccolor.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jcdctmgr.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jchuff.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jcinit.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jcmainct.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jcmarker.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jcmaster.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jcomapi.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jcparam.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jcprepct.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jcsample.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jctrans.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jdapimin.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jdapistd.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jdarith.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jdatadst.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jdatasrc.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jdcoefct.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jdcolor.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jddctmgr.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jdhuff.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jdinput.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jdmainct.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jdmarker.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jdmaster.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jdmerge.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jdpostct.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jdsample.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jdtrans.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jerror.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jfdctflt.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jfdctfst.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jfdctint.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jidctflt.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jidctfst.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jidctint.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jmemmgr.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jmemnobs.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jquant1.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jquant2.c \
	$(LIBS)/src/android/freeImage/LibJPEG/jutils.c \
	$(LIBS)/src/android/freeImage/LibJPEG/rdbmp.c \
	$(LIBS)/src/android/freeImage/LibJPEG/rdcolmap.c \
	$(LIBS)/src/android/freeImage/LibJPEG/rdgif.c \
	$(LIBS)/src/android/freeImage/LibJPEG/rdppm.c \
	$(LIBS)/src/android/freeImage/LibJPEG/rdrle.c \
	$(LIBS)/src/android/freeImage/LibJPEG/rdswitch.c \
	$(LIBS)/src/android/freeImage/LibJPEG/rdtarga.c \
	$(LIBS)/src/android/freeImage/LibJPEG/transupp.c \
	$(LIBS)/src/android/freeImage/LibJPEG/wrbmp.c \
	$(LIBS)/src/android/freeImage/LibJPEG/wrgif.c \
	$(LIBS)/src/android/freeImage/LibJPEG/wrppm.c \
	$(LIBS)/src/android/freeImage/LibJPEG/wrrle.c \
	$(LIBS)/src/android/freeImage/LibJPEG/wrtarga.c \
	$(LIBS)/src/android/freeImage/LibPNG/png.c \
	$(LIBS)/src/android/freeImage/LibPNG/pngerror.c \
	$(LIBS)/src/android/freeImage/LibPNG/pngget.c \
	$(LIBS)/src/android/freeImage/LibPNG/pngmem.c \
	$(LIBS)/src/android/freeImage/LibPNG/pngpread.c \
	$(LIBS)/src/android/freeImage/LibPNG/pngread.c \
	$(LIBS)/src/android/freeImage/LibPNG/pngrio.c \
	$(LIBS)/src/android/freeImage/LibPNG/pngrtran.c \
	$(LIBS)/src/android/freeImage/LibPNG/pngrutil.c \
	$(LIBS)/src/android/freeImage/LibPNG/pngset.c \
	$(LIBS)/src/android/freeImage/LibPNG/pngtrans.c \
	$(LIBS)/src/android/freeImage/LibPNG/pngwio.c \
	$(LIBS)/src/android/freeImage/LibPNG/pngwrite.c \
	$(LIBS)/src/android/freeImage/LibPNG/pngwtran.c \
	$(LIBS)/src/android/freeImage/LibPNG/pngwutil.c \
	$(LIBS)/src/android/freeImage/Metadata/Exif.cpp \
	$(LIBS)/src/android/freeImage/Metadata/FIRational.cpp \
	$(LIBS)/src/android/freeImage/Metadata/FreeImageTag.cpp \
	$(LIBS)/src/android/freeImage/Metadata/IPTC.cpp \
	$(LIBS)/src/android/freeImage/Metadata/TagConversion.cpp \
	$(LIBS)/src/android/freeImage/Metadata/TagLib.cpp \
	$(LIBS)/src/android/freeImage/LibOpenJPEG/bio.c \
	$(LIBS)/src/android/freeImage/LibOpenJPEG/cidx_manager.c \
	$(LIBS)/src/android/freeImage/LibOpenJPEG/cio.c \
	$(LIBS)/src/android/freeImage/LibOpenJPEG/dwt.c \
	$(LIBS)/src/android/freeImage/LibOpenJPEG/event.c \
	$(LIBS)/src/android/freeImage/LibOpenJPEG/image.c \
	$(LIBS)/src/android/freeImage/LibOpenJPEG/j2k.c \
	$(LIBS)/src/android/freeImage/LibOpenJPEG/j2k_lib.c \
	$(LIBS)/src/android/freeImage/LibOpenJPEG/jp2.c \
	$(LIBS)/src/android/freeImage/LibOpenJPEG/jpt.c \
	$(LIBS)/src/android/freeImage/LibOpenJPEG/mct.c \
	$(LIBS)/src/android/freeImage/LibOpenJPEG/mqc.c \
	$(LIBS)/src/android/freeImage/LibOpenJPEG/openjpeg.c \
	$(LIBS)/src/android/freeImage/LibOpenJPEG/phix_manager.c \
	$(LIBS)/src/android/freeImage/LibOpenJPEG/pi.c \
	$(LIBS)/src/android/freeImage/LibOpenJPEG/ppix_manager.c \
	$(LIBS)/src/android/freeImage/LibOpenJPEG/raw.c \
	$(LIBS)/src/android/freeImage/LibOpenJPEG/t1.c \
	$(LIBS)/src/android/freeImage/LibOpenJPEG/t2.c \
	$(LIBS)/src/android/freeImage/LibOpenJPEG/tcd.c \
	$(LIBS)/src/android/freeImage/LibOpenJPEG/tgt.c \
	$(LIBS)/src/android/freeImage/LibOpenJPEG/thix_manager.c \
	$(LIBS)/src/android/freeImage/LibOpenJPEG/tpix_manager.c
include $(BUILD_STATIC_LIBRARY)

#----------------------------------------------------------------------------------------
# curl (source build, no ssl — loopback http only)
include $(CLEAR_VARS)
LOCAL_MODULE := curl
LOCAL_CFLAGS += -O1 -DHAVE_CONFIG_H -Wno-pointer-arith -Wno-write-strings \
  -Wno-unused-parameter -Wno-sign-compare -Wno-missing-declarations \
  -Wno-missing-prototypes -Wno-strict-prototypes -Wno-format
LOCAL_C_INCLUDES += $(LIBS)/src/android/curl
LOCAL_C_INCLUDES += $(LIBS)/src/android/curl/lib
LOCAL_C_INCLUDES += $(LIBS)/include/android/curl
LOCAL_C_INCLUDES += $(LIBS)/include/android/curl/64
LOCAL_C_INCLUDES += $(LIBS)/include/android/zlib
LOCAL_SRC_FILES := $(shell find $(LIBS)/src/android/curl -name '*.c' -not -path '*/tests/*' -not -path '*/docs/*' -not -path '*/include/*')
LOCAL_STATIC_LIBRARIES := zlib
include $(BUILD_STATIC_LIBRARY)

#----------------------------------------------------------------------------------------
# cpr
include $(CLEAR_VARS)
LOCAL_MODULE := cpr
LOCAL_CFLAGS += -O1 $(COMMON_FLAGS)
LOCAL_C_INCLUDES += $(LIBS)/include/android/cpr
LOCAL_C_INCLUDES += $(LIBS)/src/android/cpr
LOCAL_C_INCLUDES += $(LIBS)/include/android/curl/64
LOCAL_C_INCLUDES += $(LIBS)/include/android/curl
LOCAL_SRC_FILES := $(shell find $(LIBS)/src/android/cpr -name '*.cpp')
LOCAL_STATIC_LIBRARIES := curl zlib
include $(BUILD_STATIC_LIBRARY)

#----------------------------------------------------------------------------------------
# hiredis
include $(CLEAR_VARS)
LOCAL_MODULE := hiredis
LOCAL_CFLAGS += -O1
LOCAL_C_INCLUDES += $(SDP)/linux/redis/include/hiredis
LOCAL_SRC_FILES := $(shell find $(SDP)/linux/redis/include/hiredis -maxdepth 1 -name '*.c')
include $(BUILD_STATIC_LIBRARY)

#----------------------------------------------------------------------------------------
# behaviac
include $(CLEAR_VARS)
LOCAL_MODULE := behaviac
LOCAL_CFLAGS += -O1 $(COMMON_FLAGS)
LOCAL_C_INCLUDES += $(BH)/inc
LOCAL_SRC_FILES := $(shell find $(BH)/src -name '*.cpp')
include $(BUILD_STATIC_LIBRARY)

#----------------------------------------------------------------------------------------
# LordCore (engine core, headless LINUX build)
include $(CLEAR_VARS)
LOCAL_MODULE := LordCore
LOCAL_CFLAGS := -DFREEIMAGE_LIB=1 -O1 $(COMMON_FLAGS)
LOCAL_C_INCLUDES += $(CORE)
LOCAL_C_INCLUDES += $(EDP)/nedmalloc/Include
LOCAL_C_INCLUDES += $(EDP)/RapidXml/Include
LOCAL_C_INCLUDES += $(EDP)/rapidjson/Include
LOCAL_C_INCLUDES += $(EDP)/FreeImage/Android/Include
LOCAL_C_INCLUDES += $(EDP)/FreeType/Android/Include
LOCAL_C_INCLUDES += $(EDP)/Zlib/Android/Include
LOCAL_C_INCLUDES += $(LIBS)/include/android/g3log
LOCAL_C_INCLUDES += $(LIBS)/include/android/curl/64
LOCAL_C_INCLUDES += $(LOGIC)
LOCAL_SRC_FILES := $(shell find $(CORE) -name '*.cpp')
LOCAL_STATIC_LIBRARIES := freeimage freetype zlib g3log
include $(BUILD_STATIC_LIBRARY)

#----------------------------------------------------------------------------------------
# Logic
include $(CLEAR_VARS)
LOCAL_MODULE := Logic
LOCAL_CFLAGS += -O0 $(COMMON_FLAGS)
LOCAL_C_INCLUDES += $(CORE)
LOCAL_C_INCLUDES += $(LOGIC)
LOCAL_C_INCLUDES += $(EDP)/rapidjson/Include
LOCAL_C_INCLUDES += $(EDP)/Zlib/Android/Include
LOCAL_C_INCLUDES += $(EDP)/FreeImage/Android/Include
LOCAL_C_INCLUDES += $(EDP)/FreeType/Android/Include
LOCAL_C_INCLUDES += $(LDP)/Android
LOCAL_C_INCLUDES += $(LDP)/src/raknet/include
LOCAL_C_INCLUDES += $(LDP)/sparsehash/linux/include
LOCAL_C_INCLUDES += $(LDP)/linux
LOCAL_C_INCLUDES += $(LDP)/cpr/linux/include
LOCAL_C_INCLUDES += $(LDP)/curl/linux/include
LOCAL_C_INCLUDES += $(LIBS)/include/android/g3log
LOCAL_C_INCLUDES += $(LIBS)/include/android/cpr
LOCAL_C_INCLUDES += $(LIBS)/src/android/cpr
LOCAL_C_INCLUDES += $(LIBS)/include/android/curl/64
LOCAL_C_INCLUDES += $(LIBS)/include/android/lua
LOCAL_C_INCLUDES += $(LIBS)/src/android/lua
LOCAL_C_INCLUDES += $(LIBS)/include/android/zlib
LOCAL_SRC_FILES := $(shell find $(LOGIC) -name '*.cpp')
LOCAL_STATIC_LIBRARIES := raknet cpr curl zlib lua g3log
include $(BUILD_STATIC_LIBRARY)

#----------------------------------------------------------------------------------------
# GameServer (executable)
include $(CLEAR_VARS)
LOCAL_MODULE := gameserver
LOCAL_MODULE_FILENAME := libgameserver
LOCAL_CFLAGS += -O0 $(COMMON_FLAGS)
LOCAL_C_INCLUDES += $(SERVER)
LOCAL_C_INCLUDES += $(CORE)
LOCAL_C_INCLUDES += $(LOGIC)
LOCAL_C_INCLUDES += $(EDP)/rapidjson/Include
LOCAL_C_INCLUDES += $(EDP)/Zlib/Android/Include
LOCAL_C_INCLUDES += $(EDP)/FreeImage/Android/Include
LOCAL_C_INCLUDES += $(EDP)/FreeType/Android/Include
LOCAL_C_INCLUDES += $(LDP)/Android
LOCAL_C_INCLUDES += $(LDP)/src/raknet/include
LOCAL_C_INCLUDES += $(LDP)/linux
LOCAL_C_INCLUDES += $(LDP)/cpr/linux/include
LOCAL_C_INCLUDES += $(LDP)/curl/linux/include
LOCAL_C_INCLUDES += $(LDP)/sparsehash/linux/include
LOCAL_C_INCLUDES += $(LDP)/libzippp/linux/include
LOCAL_C_INCLUDES += $(LIBS)/include/android/g3log
LOCAL_C_INCLUDES += $(LIBS)/include/android/cpr
LOCAL_C_INCLUDES += $(LIBS)/src/android/cpr
LOCAL_C_INCLUDES += $(LIBS)/include/android/curl/64
LOCAL_C_INCLUDES += $(LIBS)/include/android/curl
LOCAL_C_INCLUDES += $(LIBS)/include/android/lua
LOCAL_C_INCLUDES += $(LIBS)/src/android/lua
LOCAL_C_INCLUDES += $(LIBS)/include/android/zlib
LOCAL_C_INCLUDES += $(SDP)/linux/mysql/include
LOCAL_C_INCLUDES += $(SDP)/linux/redis/include
LOCAL_C_INCLUDES += $(SDP)/linux/behaviac/include
LOCAL_C_INCLUDES += $(BH)/inc
LOCAL_C_INCLUDES += $(SPLITS)
LOCAL_SRC_FILES := $(shell find $(SERVER) -name '*.cpp')
LOCAL_SRC_FILES := $(filter-out %/ServerNetwork_PacketRegister100.cpp %/ServerNetwork_PacketRegister200.cpp %/ServerNetwork_PacketRegister300.cpp %/ServerNetwork_PacketRegister400.cpp,$(LOCAL_SRC_FILES))
LOCAL_SRC_FILES += $(wildcard $(SPLITS)/ServerNetwork_PacketRegister*.cpp) $(wildcard $(SPLITS)/preg*.cpp)
LOCAL_STATIC_LIBRARIES := Logic LordCore raknet cpr curl zlib lua g3log behaviac freetype freeimage hiredis
LOCAL_LDLIBS := -llog -landroid -lz -ldl -lm
include $(BUILD_EXECUTABLE)
