#!/usr/bin/env python3
"""Generate docs/COVERAGE.json — machine-readable API coverage report.

Sources of truth:
- localapi-server/src/com/localapi/RoutingTable.java  (discovered + implemented)
- scripts/test_server_host.py                          (host-tested paths)
- scripts/ui_automation_test.py                        (client-exercised paths)

Status per endpoint:
- "implemented": H: handler (real state-backed behavior)
- "default":     schema-true static default ({} / [] / "" / 0 / false / none)
- "tested":      endpoint path appears in the host test suite
- "client_seen": endpoint path pattern appears in the UI automation assertions
"""
import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TABLE = os.path.join(REPO, "localapi-server", "src", "com", "localapi", "RoutingTable.java")
HOST = os.path.join(REPO, "scripts", "test_server_host.py")
UI = os.path.join(REPO, "scripts", "ui_automation_test.py")


def load_routes():
    routes = []
    with open(TABLE) as f:
        for m in re.finditer(r'"([A-Z]+) ([^|]+)\|([^"]+)"', f.read()):
            verb, path, kind = m.group(1), m.group(2), m.group(3)
            routes.append({
                "verb": verb,
                "path": path,
                "kind": kind,
                "implemented": kind.startswith("H:"),
                "handler": kind[2:] if kind.startswith("H:") else None,
            })
    return routes


def concrete_paths(source):
    """Literal path fragments used by the test suites (strip query strings)."""
    out = set()
    for m in re.finditer(r'"(/[A-Za-z0-9\-._{}/]+)', source):
        p = m.group(1)
        p = p.split("?")[0]
        if len(p) > 4:
            out.add(p)
    return out


def main():
    routes = load_routes()
    host_paths = concrete_paths(open(HOST).read()) if os.path.exists(HOST) else set()
    ui_paths = concrete_paths(open(UI).read()) if os.path.exists(UI) else set()

    report = []
    for r in routes:
        tested = any(hp == r["path"] or r["path"].startswith(hp.rstrip("*"))
                     for hp in host_paths)
        client_seen = any(up == r["path"] or r["path"].startswith(up.rstrip("*"))
                          for up in ui_paths)
        status = "implemented" if r["implemented"] else "default"
        report.append({
            "verb": r["verb"],
            "path": r["path"],
            "status": status,
            "handler": r["handler"],
            "host_tested": tested,
            "client_asserted": client_seen,
        })

    summary = {
        "discovered": len(report),
        "implemented": sum(1 for x in report if x["status"] == "implemented"),
        "default": sum(1 for x in report if x["status"] == "default"),
        "host_tested": sum(1 for x in report if x["host_tested"]),
        "client_asserted": sum(1 for x in report if x["client_asserted"]),
    }

    doc = {
        "_comment": ("Generated by scripts/gen_coverage.py — do not edit by hand. "
                     "'implemented' = state-backed handler; 'default' = schema-true "
                     "static response; 'host_tested' = exercised by "
                     "scripts/test_server_host.py; 'client_asserted' = exercised "
                     "in UI automation (app or adb-forward)."),
        "summary": summary,
        "endpoints": report,
    }
    out = os.path.join(REPO, "docs", "COVERAGE.json")
    with open(out, "w") as f:
        json.dump(doc, f, indent=1)
    print("wrote %s: %d discovered, %d implemented, %d default, %d host-tested"
          % (out, summary["discovered"], summary["implemented"],
             summary["default"], summary["host_tested"]))
    return 0


if __name__ == "__main__":
    sys.exit(main())
